### PR TITLE
Update .gitignore to ignore .iml (IntelliJ IDEA) files

### PR DESCRIPTION
**Pull request by VladRassokhin**

### CODE REVIEW

**Comment by cbeust** [comment]
I tend to check in the .iml files, do you have something against it?

**Comment by VladRassokhin** [comment]
It would be overridden during 'import from gradle' anyway and it stores nothing useful (what will not be generated during import)

**Comment by Onizuka89** [comment]
If that's the case, then why is the only change in this pull request the .gitignore? Shouldn't the .iml file(s) be removed in the pull request too? Do one need an initial .iml?

**Comment by VladRassokhin** [comment]
Already in master

**Pull request closed without merging**
