### PR TITLE
Bump kotlin, allow any datatype as key in JsonObject

### PR DESCRIPTION
**Pull request by Bixilon**
Hi there,

pretty much the same as the title tells you.

Thanks  
Moritz

### CODE REVIEW

**Review by cedricbeust-okta — COMMENTED** [review]
Curious: what's the value of allowing any value as key instead of only strings?

**Comment by Bixilon** [comment]
I have a special application, where I generate data in a binary format and in json. The binary format benefits from number keys, json can't do it, so the library needs to automatically convert the int keys in my map to a string.

It is not exactly correct to allow any key, but the key gets saved (and loaded) as String, so I don't have to create a second map with a stringifyed key.

**Comment by cedricbeust-okta** [comment]
I'd like to see if there are other use cases than yours before actually supporting this.

**Comment by Bixilon** [comment]
I can understand it, but it is not harming anything (I guess), you can still use it as before.

**Comment by Bixilon** [comment]
Actually it creates some issues, because everybody needs to cast their key to an string, so updating isn't that easy. To follow:

**Pull request closed without merging**
