### PR TITLE
update version to 0.15

### PR DESCRIPTION
**Pull request by fboldog**
Hi,

could you publish a new version with current changes?
Last setted version (from rfc compatibilty) already published as M13 update. :)

### CODE REVIEW

**Comment by fboldog** [comment]
@cbeust what do you think? :)

**Comment by cbeust** [comment]
Sure thing, will push a 0.15 shortly.

**Comment by fboldog** [comment]
:bow:

**Comment by cbeust** [comment]
Done, klaxon 0.15 is now on JCenter.

**Pull request closed without merging**
