### PR TITLE
Followup: Allow any data type as key, Improvements

### PR DESCRIPTION
**Pull request by Bixilon**
Followup of #340

### CODE REVIEW

**Comment by Bixilon** [comment]
Any update to this?

**Comment by cedricbeust-okta** [comment]
Couple of thoughts:

- If the PR says "Allows any data type as key", then the only changes should be to do that. This PR contains a lot of other stuff which, while useful, should be in a separate PR to keep the commit log clean and easier to revert.
- What's gained by allowing any data types as keys?

**Comment by Bixilon** [comment]
I made seperate commits for everything, this is imho fine. Is it not?

## Why?
As I already stated [here](https://github.com/cbeust/klaxon/pull/340#issuecomment-892904847), I am the developer of an applcaition that generates various data from minecraft. I am exporting this data into 2/3 formats. The first one is a binary format, comparable with nbt. This format allows numbers as key (json does not!). I also export it into json and minified json. JSON does not allow an int as key, therefore should automatically call `::toString` to not violate the format. It should simply not be needed to  create a separate data object expecially for json.

Java does not know generic types (like the String key in the JsonObject) in runtime. It is just checked at compile time. I can simply cast a `Map<Any, Any>` to `Map<String, Int`. It just may fail when processing something with it. I am casting my map to a string key map but in klaxon I still have to call toString.

**Comment by cbeust** [comment]
Understood, but even that commit contains extra changes that don't need to be there, such as calling `joinToString()` with a string instead of a `char`.

Realistically, this PR should only contain `result.append(Render.renderString(k.toString())).append(':')` and the test.

Would you mind opening a new PR (after rebasing, I just pushed a small change) with just these changes? Happy to merge then.

Thanks!

**Comment by Bixilon** [comment]
Whatever, see #345

**Pull request closed without merging**
