### PR TITLE
compile with java 1.7 to allow use in android

### PR DESCRIPTION
**Pull request by fboldog**

### CODE REVIEW

**Comment by cy6erGn0m** [comment]
Why do you need it? Kotlin will produce java6's bytecode anyway

**Comment by fboldog** [comment]
Yes, that true. But the KlaxonDoc.java is compiled with the default (actually 1.8) sdk level.
> hyperion:~ fboldog$ unzip -p ~/.gradle/caches/modules-2/files-2.1/com.beust/klaxon/0.25/deb18217710411ab1279cdcfcbd108baeb05ef30/klaxon-0.25.jar com/beust/klaxon/KlaxonDoc.class | hexdump -n 8
> 0000000 ca fe ba be 00 00 00 34

**Comment by cy6erGn0m** [comment]
Then it just need to be removed as it's only purpose is to create empty jar. I believe it could be done by the corresponding gradle task

**Comment by fboldog** [comment]
:+1:

**Pull request closed without merging**
